config/routes.rb
ARM::Application.routes.draw do
  resources :projects

  devise_for :users

  get 'about' => 'pages#about'

  root :to => 'pages#home'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :budgetHours, :created, :createdby, :description, :enddate, 
  :id, :modified, :modifiedby, :name, :startdate, :status

  validates :name, presence: true
  validates :user_id, presence: true
  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  	#content
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = current_user.projects.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = current_user.projects.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = current_user.projects.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<%= link_to "Audit Resource Management", "http://arm.herokuapp.com" %> by Aaron Hubbart
	</small>
</div>

app/views/layouts/_header.html.erb


<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Audit Resource Management", root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
        <ul class="nav">
      		<li><%= link_to "Home", root_path %></li>
      		<li><%= link_to "About Us", about_path %></li>
    	</ul>
		
		  <ul class="nav pull-right">
      	<% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
	<title>Audit Resource Management</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		
		<div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>		
	</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	This project is inspired by the pure lack of resource management tools available for audit companies or departments.  I have evaluated numerous options and none seem to fit the need or process of an audit shop.  Hopefully I can make something better.<br /><br />
	View my site on <%= link_to "Github", "https://github.com/abhubbart/ARM" %>!<br />
	View my site on <%= link_to "Heroku", "http://arm.herokuapp.com/" %>!
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
    <h1>You're logged in!</h1>
<% else %>
	<div class="hero-unit">
		<h1>Welcome to Audit Resource Management!</h1>
		<p>
			You've found the home page for the 
			<%= link_to "Audit Resource Management", "http://arm.herokuapp.com" %>
			application.
		</p>
		<p>
			<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
		</p>
	</div>
<% end %>

app/views/projects/_form.html.erb
<%= simple_form_for(@project, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  
    <%= f.input :id %>
    <%= f.input :name %>
    <%= f.input :description, as: :text, input_html: { rows: "3"} %>
    <%= f.input :startdate %>
    <%= f.input :enddate %>
    <%= f.input :budgetHours %>
    <%= f.input :status %>
    <%= f.input :createdby %>
    <%= f.input :created %>
    <%= f.input :modifiedby %>
    <%= f.input :modified %>
  

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<tr>
    <td><%= project.id %></td>
    <td><%= project.name %></td>
    <td><%= project.description %></td>
    <td><%= project.startdate %></td>
    <td><%= project.enddate %></td>
    <td><%= project.budgetHours %></td>
    <td><%= project.status %></td>
    <td><%= project.createdby %></td>
    <td><%= project.created %></td>
    <td><%= project.modifiedby %></td>
    <td><%= project.modified %></td>
    <td><%= link_to 'Show', project %></td>
    <% if current_user == project.user %>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
</tr>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Project Listing</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Description</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Budgethours</th>
      <th>Status</th>
      <th>Createdby</th>
      <th>Created</th>
      <th>Modifiedby</th>
      <th>Modified</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render @projects %>
  </tbody>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="row">
  <div class="span6 offset3">
    <div class="well">
      <p>
        <b>Id:</b>
        <%= @project.id %>
      </p>

      <p>
        <b>Name:</b>
        <%= @project.name %>
      </p>

      <p>
        <b>Description:</b>
        <%= @project.description %>
      </p>

      <p>
        <b>Startdate:</b>
        <%= @project.startdate %>
      </p>

      <p>
        <b>Enddate:</b>
        <%= @project.enddate %>
      </p>

      <p>
        <b>Budgethours:</b>
        <%= @project.budgetHours %>
      </p>

      <p>
        <b>Status:</b>
        <%= @project.status %>
      </p>

      <p>
        <b>Createdby:</b>
        <%= @project.createdby %>
      </p>

      <p>
        <b>Created:</b>
        <%= @project.created %>
      </p>

      <p>
        <b>Modifiedby:</b>
        <%= @project.modifiedby %>
      </p>

      <p>
        <b>Modified:</b>
        <%= @project.modified %>
      </p>

      <p>
        <b>Modified By:</b>
        <%= @project.user.name %>
      </p>
      <% if current_user == @project.user %>
        <%= link_to 'Edit', edit_project_path(@project) %> |
      <% end %>
      <%= link_to 'Back', projects_path %>
    </div>
  </div>
</div>